# Site settings
author: Marcos Rodriguez
title: 
header-img: img/home-bg.png
email: m.rodrig.felix@gmail.com
copyright_name: Marcos Rodriguez
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: MarcFelixRodrig
github_username:  MarcRodrigFelix

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
